### ISSUE TITLE
Interesting in Arabic Khatt

### ISSUE THREAD

**Issue by TouailabIlyass** [DigitalKhatt/visualmetafont#1]
Good Morning,
Im Touailab Ilyass, I'm a software engineer, I'm very interested in your project, and I'm interested in Arabic Calligraphy I want to contact you for some help and questions.
I will send you my phone contact and e-mail if you want to help me.
Thank you.
Telephone: +2126 29 49 65 77.
Mail: ilyase.touailab@edu.uca.ma

**Comment by aminanan** [comment]
To share the information with all the community please file a new issue describing the problem. You can also post your question at [https://twitter.com/DigitalKhatt](https://twitter.com/DigitalKhatt). Thanks.
