### ISSUE TITLE
#Interesting to make font of new Mus'haf Al-Madinah

### ISSUE THREAD

**Issue by Muslim010101** [DigitalKhatt/visualmetafont#2]
السلام عليكم 
Can you help me, how to convert this new Mus'haf Madinah in otf format, this new Mus'haf Al-Madinah exist here in AI format: https://dm.qurancomplex.gov.sa
![20210324_061927](https://user-images.githubusercontent.com/52772116/112259642-eddb6d00-8c68-11eb-8a6e-0782cf703d8a.jpg)

**Comment by aminanan** [comment]
و عليكم السلام
This is one of the goals of the project : Typeset a high quality digital version comparable to the handwritten one. You can follow the progress at [https://twitter.com/DigitalKhatt](https://twitter.com/DigitalKhatt).

**Comment by Muslim629** [comment]
> و عليكم السلام
> This is one of the goals of the project : Typeset a high quality digital version comparable to the handwritten one. You can follow the progress at https://twitter.com/DigitalKhatt.

But this one is new Mus'haf Madinah 1441 my brother, last Calligraphy Naskh .

**Comment by Muslim010101** [comment]
![20210425_150002](https://user-images.githubusercontent.com/52772116/116153755-1d5a1b00-a6e8-11eb-99d8-06fac8bccb92.jpg)

السلام عليكم  My brother did you vectorize and decoration frame outside ayaat or you vetorize just banner of name Surah ?

**Comment by Muslim010101** [comment]
> و عليكم السلام
> This is one of the goals of the project : Typeset a high quality digital version comparable to the handwritten one. You can follow the progress at https://twitter.com/DigitalKhatt.

Oh soo good  بارك الله فيك 
Are you working on it this year?
